<a href="https://colab.research.google.com/github/tanpharamut/Sort-images-into-folders/blob/main/Sort_images_V1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import pandas as pd
import os
import glob
import re

In [14]:
from google.colab import drive

In [15]:
path = '/content/drive/MyDrive/unsup-car-dataset/freiburg_static_cars_52_v1.1/annotations/1_annot.txt'

In [16]:
print(path)

/content/drive/MyDrive/unsup-car-dataset/freiburg_static_cars_52_v1.1/annotations/1_annot.txt

In [20]:
df = pd.read_csv(path, delimiter = "\t").head()
df

   car001/left-0001.ppm   3 65 886 346   3
0  car001/left-0017.ppm   1 63 874 341   3
1  car001/left-0033.ppm   1 56 845 330   4
2  car001/left-0049.ppm   6 81 849 361   7
3  car001/left-0065.ppm  20 96 859 380   9
4  car001/left-0081.ppm  1 127 830 405  11

In [25]:
df2 = pd.read_csv(path, sep=" ", header=None, names=["a", "b", "c", "d"])
df2

                             a   b    c        d
0      car001/left-0001.ppm\t3  65  886   346\t3
1      car001/left-0017.ppm\t1  63  874   341\t3
2      car001/left-0033.ppm\t1  56  845   330\t4
3      car001/left-0049.ppm\t6  81  849   361\t7
4     car001/left-0065.ppm\t20  96  859   380\t9
..                         ...  ..  ...      ...
117  car001/left-1873.ppm\t123  93  899  390\t17
118   car001/left-1889.ppm\t97  62  888  346\t17
119   car001/left-1905.ppm\t36  71  843  329\t17
120    car001/left-1921.ppm\t1  76  812  333\t16
121    car001/left-1937.ppm\t1  72  838  321\t16

[122 rows x 4 columns]

In [27]:
path_car01 = '/content/drive/MyDrive/unsup-car-dataset/freiburg_static_cars_52_v1.1/car001'